#!/usr/bin/python
# collatz.py
# Collatz conjecture - Given any initial natural number, 
# consider the sequence of numbers generated by repeatedly following the rule:
# divide by two if the number is even or
# multiply by 3 and add 1 if the number is odd.
# The Collatz conjecture states that this sequence always terminates at 1
# This program asks for a number as input and generates the sequence terminating at 1

import sys

def collatz(number):
  if number % 2 == 0:
    num_floor =  number // 2
    print num_floor
    return num_floor
  elif number % 2 == 1:
    num_expr = 3 * number + 1
    print num_expr
    return num_expr
  else:
    print "Number is neither even nor odd, what is it?"

num = raw_input("Enter a number: ");

try:
  int_number = int(num)
except ValueError:
  print "You must type an integer"
  sys.exit()

ret_val = collatz(int_number)

while True:
  if ret_val == 1:
    break;
  else:
    number = ret_val

  ret_val = collatz(number)
  
